### ISSUE TITLE
Can't run on Ubuntu 20.04; package providing python gtk module (python-gtk2) no longer available

### ISSUE THREAD

**Issue by juozaspo** [Podshot/MCEdit-Unified#1001]
#### Description of Issue:
MCedit-Unified does not run in Ubuntu 20.04 LTS. It requires a gtk module which is no longer available on Ubuntu repositories as it requires python package which is removed from 20.04 LTS. Pip package for python2 is missing too. Packages python2 & python3 are available though.
#### MCEdit Version:
90abfb170c65b877ac67193e717fa3a3ded635dd (latest available git master)
#### Minecraft Version the world was last opened in:
N/A
#### Operating System:
Ubuntu Linux 20.04 LTS
#### A screenshot or full text of the error from the console:
```
juozas@xubuntu:~/MCEdit/MCEdit-Unified$ ./mcedit.sh 
Starting MCEdit...
Running in fixed mode. Support files are in your Documents folder.
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Splash load...
[ ****** ] ~~~~~~~~~~ Starting MCEdit-Unified v1.6.0.0
Traceback (most recent call last):
  File "mcedit.py", line 114, in <module>
    import keys
  File "/home/juozas/MCEdit/MCEdit-Unified/keys.py", line 4, in <module>
    import albow
  File "/home/juozas/MCEdit/MCEdit-Unified/albow/__init__.py", line 16, in <module>
    from albow.fields import TextField, FloatField, IntField, TimeField, TextFieldWrapped, Field
  File "/home/juozas/MCEdit/MCEdit-Unified/albow/fields.py", line 21, in <module>
    import pyperclip
  File "/home/juozas/MCEdit/MCEdit-Unified/pyperclip.py", line 179, in <module>
    raise Exception('Pyperclip requires the gtk module installed or the xclip command.')
Exception: Pyperclip requires the gtk module installed or the xclip command.
Press any key to close.
```
#### How to reproduce:
- Try to run MCEdit-Unified on Ubuntu Linux 20.04, get error about missing gtk module
- Try to install gtk module, find out that packages named python, python-gtk2 or python-gtk3 are missing from repository
- Try to search for similar matching packages by running `apt-cache search python|grep -i gtk`, find no useful alternatives
- Try to find pip to install for python2, note there's no such package, only available pip package is named python3-pip, providing pip3 binary

**Comment by freundTech** [comment]
Ubuntu 20.04 dropped support for python2 in favour of python3. MCEdit still depends on python2 and a python3 port is unlikely to happen.
You could try to get it to work using `pyenv` or install the necessary dependencies manually.
Amulet, the work in progress successor to MCEdit will support python3.
