### ISSUE TITLE
Wont load world

### ISSUE THREAD

**Issue by KalJames** [Podshot/MCEdit-Unified#1003]
MCEdit Unified bug report template. For MCEdit 2.0 bugs see here : https://github.com/mcedit/mcedit2
World loads in MC, Refuses to load into MCedit.
Newest version as of 2018 [two years ago]
MC v1.15.2
Windows 10 x64
An error occurred while opening C:\Users\Anim4\AppData\Roaming\.minecraft\saves\IJAMinecraft's Death Star
'PySide.QtGui.QLineEdit.setText' called with wrong argument types:
  PySide.QtGui.QLineEdit.setText(list)
Supported signatures:
  PySide.QtGui.QLineEdit.setText(unicode)

Traceback (most recent call last):
  File "mcedit2\editorapp.py", line 790, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 430, in __init__ (self is a EditorSession)
  File "mcedit2\panels\worldinfo.py", line 90, in __init__ (self is a WorldInfoPanel)
  File "mcedit2\panels\worldinfo.py", line 97, in updatePanel (self is a WorldInfoPanel)
  File "mcedit2\panels\worldinfo.py", line 115, in _updatePanel (self is a WorldInfoPanel)
TypeError: 'PySide.QtGui.QLineEdit.setText' called with wrong argument types:
  PySide.QtGui.QLineEdit.setText(list)
Supported signatures:
  PySide.QtGui.QLineEdit.setText(unicode)
I downloaded the map from https://ijaminecraft.com/map/death-star/
and loaded into MC before running it in MCedit to make sure it works. then MCedit refuses load it. it loads maps from years ago including 1.13+ maps but not this one.
[IJAMinecrafts-Death-Star.zip](https://github.com/Podshot/MCEdit-Unified/files/4647155/IJAMinecrafts-Death-Star.zip)

**Comment by Podshot** [comment]
This is a bug with MCEdit 2.0 which is a separate project. Please report it at the correct GitHub repository: https://github.com/mcedit/mcedit2
