### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Pato2222** [Podshot/MCEdit-Unified#1016]
MCEdit Unified bug report template. For MCEdit 2.0 bugs see here : https://github.com/mcedit/mcedit2
#### A screenshot or full text of the error from the console:                                     
                                                                                                                                      An error occurred while opening C:\Users\pato\AppData\Roaming\.minecraft\saves\hola buen
'NoneType' object is not iterable

Traceback (most recent call last):
  File "mcedit2\editorapp.py", line 790, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 419, in __init__ (self is a EditorSession)
  File "mcedit2\editorsession.py", line 724, in setConfiguredBlocks (self is a EditorSession)
  File "mcedit2\editorsession.py", line 728, in reloadModels (self is a EditorSession)
  File "src\mcedit2\rendering\blockmodels.pyx", line 236, in mcedit2.rendering.blockmodels.BlockModels.__init__  
  File "src\mcedit2\rendering\blockmodels.pyx", line 278, in mcedit2.rendering.blockmodels.BlockModels.loadModelParts  
TypeError: 'NoneType' object is not iterable

## Read before submitting
If we are not able to reproduce the error, we may ask for you to submit a world so we can test it. Same process for schematics.
If you have included enough information for each section, please delete the above header and all the text below.

**Comment by QuentinBhn** [comment]
Bonjour, j'aimerais savoir comment régler le problème.

J'ai exactement le même problème sur exactement les mêmes choses sur la même version de McEdit, sauf que aucune réponse n'a été donné, je ne sais donc pas résoudre le problème ...

Pouvez-vous m'aider ?

**Comment by Dushess** [comment]
@QuentinBhn Just wrong tracker...
