### ISSUE TITLE
Throw out UnicodeDecodeError while starting mcedit on Windows 10

### ISSUE THREAD

**Issue by nukemiko** [Podshot/MCEdit-Unified#1020]
#### A screenshot or full text of the error from the console:
```
PS C:\Users\Public\mcedit2-win64-2.0.0-beta14> .\mcedit2.exe
[10320] PyInstaller Bootloader 3.x
[10320] LOADER: executable is C:\Users\Public\mcedit2-win64-2.0.0-beta14\mcedit2.exe
[10320] LOADER: homepath is C:\Users\Public\mcedit2-win64-2.0.0-beta14
[10320] LOADER: _MEIPASS2 is NULL
[10320] LOADER: archivename is C:\Users\Public\mcedit2-win64-2.0.0-beta14\mcedit2.exe
[10320] LOADER: Extracting binaries
[10320] LOADER: Executing self as child
[10320] LOADER: set _MEIPASS2 to C:\Users\鏃堕洦缁綏\AppData\Local\Temp\_MEI103202
[10320] LOADER: Setting up to run child
[10320] LOADER: Creating child process
[10320] LOADER: Waiting for child process to finish...
[15532] PyInstaller Bootloader 3.x
[15532] LOADER: executable is C:\Users\Public\mcedit2-win64-2.0.0-beta14\mcedit2.exe
[15532] LOADER: homepath is C:\Users\Public\mcedit2-win64-2.0.0-beta14
[15532] LOADER: _MEIPASS2 is C:\Users\鏃堕洦缁綏\AppData\Local\Temp\_MEI103202
[15532] LOADER: archivename is C:\Users\Public\mcedit2-win64-2.0.0-beta14\mcedit2.exe
[15532] LOADER: SetDllDirectory(C:\Users\鏃堕洦缁綏\AppData\Local\Temp\_MEI103202)
[15532] LOADER: Already in the child - running user's code.
[15532] LOADER: manifestpath: C:\Users\鏃堕洦缁綏\AppData\Local\Temp\_MEI103202\mcedit2.exe.manifest
[15532] LOADER: Activation context created
[15532] LOADER: Activation context activated
[15532] LOADER: Python library: C:\Users\鏃堕洦缁綏\AppData\Local\Temp\_MEI103202\python27.dll
[15532] LOADER: Loaded functions from Python library.
[15532] LOADER: Manipulating environment (sys.path, sys.prefix)
[15532] LOADER: sys.prefix is C:\Users\时雨绮罗\AppData\Local\Temp\_MEI10~1
[15532] LOADER: Setting runtime options
[15532] LOADER: Bootloader option: pyi-windows-manifest-filename mcedit2.exe.manifest
[15532] LOADER: Initializing python
[15532] LOADER: Overriding Python's sys.path
[15532] LOADER: Post-init sys.path is C:\Users\鏃堕洦缁綏\AppData\Local\Temp\_MEI103202
[15532] LOADER: Setting sys.argv
[15532] LOADER: setting sys._MEIPASS
[15532] LOADER: importing modules from CArchive
[15532] LOADER: extracted struct
[15532] LOADER: callfunction returned...
[15532] LOADER: extracted pyimod01_os_path
[15532] LOADER: callfunction returned...
[15532] LOADER: extracted pyimod02_archive
[15532] LOADER: callfunction returned...
[15532] LOADER: extracted pyimod03_importers
[15532] LOADER: callfunction returned...
[15532] LOADER: Installing PYZ archive with Python modules.
[15532] LOADER: PYZ archive: out00-PYZ.pyz
[15532] LOADER: Running pyiboot01_bootstrap.py
[15532] LOADER: Running pyi_rth_win32comgenpy.py
[15532] LOADER: Running pyi_rth_pkgres.py
[15532] LOADER: Running pyi_rth_multiprocessing.py
[15532] LOADER: Running pyi_rth_traitlets.py
[15532] LOADER: Running pyi_rth_qt4plugins.py
[15532] LOADER: Running main.py
Logging level set
sys.frozen is set
Logging to C:\Users\Public\mcedit2-win64-2.0.0-beta14\MCEdit 2 Files\mcedit2.log
Setting up console handler
Traceback (most recent call last):
  File "mcedit2\main.py", line 226, in <module>
  File "mcedit2\main.py", line 222, in main
  File "mcedit2\util\profiler.py", line 73, in _wrapper
  File "mcedit2\main.py", line 172, in startup
  File "mcedit2\sentry.py", line 15, in get_sentry_client
  File "site-packages\raven\base.py", line 177, in __init__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb8 in position 0: ordinal not in range(128)
[15532] Failed to execute script main
[15532] LOADER: OK.
[15532] LOADER: Cleaning up Python interpreter.
[10320] LOADER: Back to parent (RC: -1)
[10320] LOADER: Doing cleanup
[10320] LOADER: Freeing archive status for C:\Users\Public\mcedit2-win64-2.0.0-beta14\mcedit2.exe
```

#### How to reproduce:
1. Log in with a username with Chinese characters (Home directory name will with Chinese characters)
2. Run mcedit2.exe in terminal
3. See the error message

**Comment by Podshot** [comment]
This is a bug with MCEdit 2.0 which is a separate project. Please report it at the correct GitHub repository: https://github.com/mcedit/mcedit2
