### ISSUE TITLE
McEdit Not Opening on Mac

### ISSUE THREAD

**Issue by Chimalus** [Podshot/MCEdit-Unified#1023]
#### Log:

Last login: Fri May 28 18:01:51 on ttys000
matthewstiles@Matthews-MacBook-Pro-2 ~ % /Users/matthewstiles/Desktop/mcedit2-macosx64-2.0.0-beta14/MCEdit\ 2.app/Contents/MacOS/MCEdit\ 2 ; exit;
[6119] PyInstaller Bootloader 3.x
[6119] LOADER: executable is /Users/matthewstiles/Desktop/mcedit2-macosx64-2.0.0-beta14/MCEdit 2.app/Contents/MacOS/MCEdit 2
[6119] LOADER: homepath is /Users/matthewstiles/Desktop/mcedit2-macosx64-2.0.0-beta14/MCEdit 2.app/Contents/MacOS
[6119] LOADER: _MEIPASS2 is NULL
[6119] LOADER: archivename is /Users/matthewstiles/Desktop/mcedit2-macosx64-2.0.0-beta14/MCEdit 2.app/Contents/MacOS/MCEdit 2
[6119] LOADER: No need to extract files to run; setting extractionpath to homepath
[6119] LOADER: Already in the child - running user's code.
[6119] LOADER: Python library: /Users/matthewstiles/Desktop/mcedit2-macosx64-2.0.0-beta14/MCEdit 2.app/Contents/MacOS/Python
[6119] LOADER: Loaded functions from Python library.
[6119] LOADER: Manipulating environment (sys.path, sys.prefix)
[6119] LOADER: sys.prefix is /Users/matthewstiles/Desktop/mcedit2-macosx64-2.0.0-beta14/MCEdit 2.app/Contents/MacOS
[6119] LOADER: Setting runtime options
[6119] LOADER: Initializing python
[6119] LOADER: Overriding Python's sys.path
[6119] LOADER: Post-init sys.path is /Users/matthewstiles/Desktop/mcedit2-macosx64-2.0.0-beta14/MCEdit 2.app/Contents/MacOS
[6119] LOADER: Setting sys.argv
[6119] LOADER: setting sys._MEIPASS
[6119] LOADER: importing modules from CArchive
[6119] LOADER: extracted struct
[6119] LOADER: callfunction returned...
[6119] LOADER: extracted pyimod01_os_path
[6119] LOADER: callfunction returned...
[6119] LOADER: extracted pyimod02_archive
[6119] LOADER: callfunction returned...
[6119] LOADER: extracted pyimod03_importers
[6119] LOADER: callfunction returned...
[6119] LOADER: Installing PYZ archive with Python modules.
[6119] LOADER: PYZ archive: out00-PYZ.pyz
[6119] LOADER: Running pyiboot01_bootstrap.py
[6119] LOADER: Running pyi_rth_pkgres.py
[6119] LOADER: Running pyi_rth_multiprocessing.py
[6119] LOADER: Running pyi_rth_traitlets.py
[6119] LOADER: Running pyi_rth_qt4plugins.py
[6119] LOADER: Running main.py
Logging level set
sys.frozen is set
OS X found.
Logging to /Users/matthewstiles/Library/Logs/mcedit2.log
Setting up console handler
[ERROR][main.py:203]:Unhandled Exception: 
	('Unable to load OpenGL library', "Failed to load dynlib/dll 'OpenGL'. Most probably this dynlib/dll was not found when the application was frozen.", 'OpenGL', None)
Traceback (most recent call last):
  File "mcedit2/main.py", line 226, in <module>  
  File "mcedit2/main.py", line 222, in main  
  File "mcedit2/util/profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2/main.py", line 188, in startup  
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module (self is a FrozenImporter)
  File "mcedit2/editorapp.py", line 14, in <module>  
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module (self is a FrozenImporter)
  File "mcedit2/plugins/__init__.py", line 13, in <module>  
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module (self is a FrozenImporter)
  File "mcedit2/editortools/generate.py", line 12, in <module>  
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module (self is a FrozenImporter)
  File "mcedit2/handles/boxhandle.py", line 10, in <module>  
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module (self is a FrozenImporter)
  File "mcedit2/rendering/scenegraph/scenenode.py", line 8, in <module>  
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module (self is a FrozenImporter)
  File "mcedit2/rendering/scenegraph/rendernode.py", line 9, in <module>  
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module (self is a FrozenImporter)
  File "OpenGL/GL/__init__.py", line 3, in <module>  
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module (self is a FrozenImporter)
  File "OpenGL/error.py", line 12, in <module>  
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module (self is a FrozenImporter)
  File "OpenGL/platform/__init__.py", line 35, in <module>  
  File "OpenGL/platform/__init__.py", line 32, in _load  
  File "OpenGL/platform/baseplatform.py", line 92, in install (self is a DarwinPlatform)
  File "OpenGL/platform/baseplatform.py", line 14, in __get__ (self is a lazy_property)
  File "OpenGL/platform/darwin.py", line 62, in GetCurrentContext (self is a DarwinPlatform)
  File "OpenGL/platform/baseplatform.py", line 14, in __get__ (self is a lazy_property)
  File "OpenGL/platform/darwin.py", line 45, in CGL (self is a DarwinPlatform)
  File "OpenGL/platform/baseplatform.py", line 14, in __get__ (self is a lazy_property)
  File "OpenGL/platform/darwin.py", line 41, in GL (self is a DarwinPlatform)
ImportError: ('Unable to load OpenGL library', "Failed to load dynlib/dll 'OpenGL'. Most probably this dynlib/dll was not found when the application was frozen.", 'OpenGL', None)
Error in sys.excepthook:
Traceback (most recent call last):
  File "mcedit2/main.py", line 217, in excepthook
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "mcedit2/dialogs/error_dialog.py", line 14, in <module>
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "mcedit2/util/qglcontext.py", line 5, in <module>
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "OpenGL/GL/__init__.py", line 3, in <module>
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "OpenGL/error.py", line 12, in <module>
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "OpenGL/platform/__init__.py", line 35, in <module>
  File "OpenGL/platform/__init__.py", line 32, in _load
  File "OpenGL/platform/baseplatform.py", line 92, in install
  File "OpenGL/platform/baseplatform.py", line 14, in __get__
  File "OpenGL/platform/darwin.py", line 62, in GetCurrentContext
  File "OpenGL/platform/baseplatform.py", line 14, in __get__
  File "OpenGL/platform/darwin.py", line 45, in CGL
  File "OpenGL/platform/baseplatform.py", line 14, in __get__
  File "OpenGL/platform/darwin.py", line 41, in GL
ImportError: ('Unable to load OpenGL library', "Failed to load dynlib/dll 'OpenGL'. Most probably this dynlib/dll was not found when the application was frozen.", 'OpenGL', None)

Original exception was:
Traceback (most recent call last):
  File "mcedit2/main.py", line 226, in <module>
  File "mcedit2/main.py", line 222, in main
  File "mcedit2/util/profiler.py", line 73, in _wrapper
  File "mcedit2/main.py", line 188, in startup
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "mcedit2/editorapp.py", line 14, in <module>
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "mcedit2/plugins/__init__.py", line 13, in <module>
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "mcedit2/editortools/generate.py", line 12, in <module>
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "mcedit2/handles/boxhandle.py", line 10, in <module>
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "mcedit2/rendering/scenegraph/scenenode.py", line 8, in <module>
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "mcedit2/rendering/scenegraph/rendernode.py", line 9, in <module>
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "OpenGL/GL/__init__.py", line 3, in <module>
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "OpenGL/error.py", line 12, in <module>
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-install-7iypVy/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "OpenGL/platform/__init__.py", line 35, in <module>
  File "OpenGL/platform/__init__.py", line 32, in _load
  File "OpenGL/platform/baseplatform.py", line 92, in install
  File "OpenGL/platform/baseplatform.py", line 14, in __get__
  File "OpenGL/platform/darwin.py", line 62, in GetCurrentContext
  File "OpenGL/platform/baseplatform.py", line 14, in __get__
  File "OpenGL/platform/darwin.py", line 45, in CGL
  File "OpenGL/platform/baseplatform.py", line 14, in __get__
  File "OpenGL/platform/darwin.py", line 41, in GL
ImportError: ('Unable to load OpenGL library', "Failed to load dynlib/dll 'OpenGL'. Most probably this dynlib/dll was not found when the application was frozen.", 'OpenGL', None)
[6119] Failed to execute script main
[6119] LOADER: OK.
[6119] LOADER: Cleaning up Python interpreter.
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

#### How to reproduce: ctrl+click the app, click Show Package Contents, go to Contents>MacOS, and open the "McEdit2" console file.

Thanks for your help.

**Comment by Dushess** [comment]
Again version 2 in Unified thread...

**Comment by woyczek** [comment]
« Again version 2 in Unified thread... » Cannot find any related thread to try solving this issue.
It IS OS specific, related to MacOS BigSur (and Monterey). It is heavily documented in the PyInstaller issue tracker.

1/ the reason:
Apple has moved the libraries
2/ what to do:
for now, the best workaround is to not rely on dyld_find to find dynamically linked DLL, but expose fullpath of the library at call.
3/ how to fix?
Upstream, certainly.
See also:
- https://github.com/pyinstaller/pyinstaller/issues/5107
- https://stackoverflow.com/questions/64954725/how-to-use-pyinstaller-for-macos-big-sur

This bug shall not be closed, and needs to be reopened!

**Comment by Dushess** [comment]
@woyczek 
![image](https://user-images.githubusercontent.com/15954961/143314853-2e31c2cd-d5c2-4126-91f4-bfd36f410f85.png)
Uhm, it is there
