### ISSUE TITLE
MCEdit 0.1.7.1 crashes upon copying blocks within selection

### ISSUE THREAD

**Issue by MatthewStevenGo** [Podshot/MCEdit-Unified#1032]
Just reset my Windows 10 OS with an option to retain data. However, whenever I try to copy within selection, it returns as follows:

Running in portable mode. MCEdit-schematics and mcedit.ini are stored alongside MCEditData
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of D:\Matthew\MCEdit-0.1.7.1 (64-bit)\ServerJarStorage named with the server's version number
Cached servers:  [u'Unknown (45)', u'Unknown (44)', u'Unknown (43)', u'Unknown (42)', u'Unknown (41)', u'Unknown (40)', u'Unknown (39)', u'Unknown (38)', u'Unknown (37)', u'Unknown (36)', u'Unknown (35)', u'Unknown (34)', u'Unknown (33)', u'Unknown (32)', u'Unknown (31)', u'Unknown (30)', u'Unknown (29)', u'Unknown (28)', u'Unknown (27)', u'Unknown (26)', u'Unknown (25)', u'Unknown (24)', u'Unknown (23)', u'Unknown (22)', u'Unknown (21)', u'Unknown (20)', u'Unknown (19)', u'Unknown (18)', u'Unknown (17)', u'Unknown (16)', u'Unknown (15)', u'Unknown (14)', u'Unknown (13)', u'Unknown (12)', u'Unknown (11)', u'Unknown (10)', u'Unknown (9)', u'Unknown (8)', u'Unknown (7)', u'Unknown (6)', u'Unknown (5)', u'Unknown (4)', u'Unknown (3)', u'Unknown (2)', u'Unknown (1)', u'Unknown']
[   ERROR][                   root.py:912]:Error while checking for updates
Traceback (most recent call last):
  File "mcedit.py", line 908, in main
  File "esky\__init__.pyo", line 787, in find_update
  File "esky\finder.pyo", line 184, in find_versions
  File "esky\finder.pyo", line 164, in open_url
  File "urllib2.pyo", line 126, in urlopen
  File "urllib2.pyo", line 400, in open
  File "urllib2.pyo", line 418, in _open
  File "urllib2.pyo", line 378, in _call_chain
  File "urllib2.pyo", line 1215, in https_open
  File "urllib2.pyo", line 1177, in do_open
URLError: <urlopen error [Errno 1] _ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
Clipping:  _Vector(x=1, y=1, z=1)
[   ERROR][                  root.py:1059]:MCEdit version 0.1.7.1
[   ERROR][                  root.py:1062]:exception: access violation writing 0xFFFFFFFF86A2CAF0
Traceback (most recent call last):
  File "mcedit.py", line 1057, in main
  File "mcedit.py", line 978, in main
  File "albow\root.pyo", line 106, in run
  File "albow\root.pyo", line 159, in run_modal
  File "albow\widget.pyo", line 730, in gl_draw_all
  File "albow\widget.pyo", line 730, in gl_draw_all
  File "albow\widget.pyo", line 730, in gl_draw_all
  File "albow\widget.pyo", line 730, in gl_draw_all
  File "albow\widget.pyo", line 730, in gl_draw_all
  File "albow\widget.pyo", line 730, in gl_draw_all
  File "albow\widget.pyo", line 730, in gl_draw_all
  File "albow\widget.pyo", line 727, in gl_draw_all
  File "albow\openglwidgets.pyo", line 23, in gl_draw_self
  File "albow\openglwidgets.pyo", line 29, in gl_draw_viewport
  File "editortools\thumbview.pyo", line 42, in gl_draw
  File "glutils.pyo", line 206, in __init__
  File "OpenGL\latebind.pyo", line 41, in __call__
  File "OpenGL\latebind.pyo", line 45, in __call__
  File "OpenGL\wrapper.pyo", line 574, in wrapperCall
WindowsError: exception: access violation writing 0xFFFFFFFF86A2CAF0
Press RETURN or close this window to dismiss.

I know it is older, but I am far well-versed with that version despite its age. Probably must be something with the GeForce control panels (I make it run GPU for graphics, and customized the FXAA, MFAA, Texture (Trilinear Filtering), as well as the triple buffering where applicable). Any feedbacks are appreciated.

**Comment by MatthewStevenGo** [comment]
Note that it is in the second hard drive, not the main drive, as it is a 256 GB NVME SSD. As well, I also have the 1.5.6.0 version of MCEdit, which has no aforementioned problem.

Note that the world I am using is in 1.12.2 versioon.

**Comment by MatthewStevenGo** [comment]
Managed to get the other copy of the 0.1.7.1, and then unzip it and it is now working. Turns out it has nothing to do with GeForce control center presets, as the same as a preceding one became kinda broken after I reset my Windows 10 while retaining the ability to keep documents and the like.

**Comment by Khroki** [comment]
Not the current version, even if this was active we wouldn't support versions below 1.5.6.0
