### ISSUE TITLE
unable to edit worlds due to message 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by freesia-moonshine** [Podshot/MCEdit-Unified#1033]
#### Description of Issue: unbale to edit worlds, error reads as follows;    An error occurred while opening C:\Users\michael\AppData\Roaming\.minecraft\saves\Acol Island
'NoneType' object is not iterable

Traceback (most recent call last):
  File "mcedit2\editorapp.py", line 790, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 419, in __init__ (self is a EditorSession)
  File "mcedit2\editorsession.py", line 724, in setConfiguredBlocks (self is a EditorSession)
  File "mcedit2\editorsession.py", line 728, in reloadModels (self is a EditorSession)
  File "src\mcedit2\rendering\blockmodels.pyx", line 236, in mcedit2.rendering.blockmodels.BlockModels.__init__  
  File "src\mcedit2\rendering\blockmodels.pyx", line 278, in mcedit2.rendering.blockmodels.BlockModels.loadModelParts  
TypeError: 'NoneType' object is not iterable

## Read before submitting
If we are not able to reproduce the error, we may ask for you to submit a world so we can test it. Same process for schematics.
If you have included enough information for each section, please delete the above header and all the text below.

**Comment by Khroki** [comment]
Wrong version of MCEdit, this is the continuation of 1.x.
