### ISSUE TITLE
MCEdit starting crashes

### ISSUE THREAD

**Issue by yuanjie000** [Podshot/MCEdit-Unified#899]
MCEdit.v1.5.6.0
win10 16299.192
```
Traceback (most recent call last):
  File "mcedit.py", line 13, in <module>
  File "C:\build\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "splash.py", line 5, in <module>
  File "C:\build\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "directories.py", line 225, in <module>
  File "ntpath.py", line 85, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 3: ordinal not in range(128)
Failed to execute script mcedit
```

**Comment by Podshot** [comment]
Can you give us the full path that the MCEdit executable resides in?

**Comment by yuanjie000** [comment]
F:\mc文件\mcedit\mcedit.exe
"文件" is Chinese characters
@Podshot

**Comment by freundTech** [comment]
Looks like a problem with pyinstaller. The error is thrown before pyinstaller loads mcedit.
A temporary workaround would be to move mcedit to a folder which doesn't contain any Unicode characters.

**Comment by yuanjie000** [comment]
when I rename folder name, mcedit working well

**Comment by Podshot** [comment]
Closing since the issue has been resolved
