### ISSUE TITLE
snip

### ISSUE THREAD

**Issue by Elpersonn** [Podshot/MCEdit-Unified#928]
snip

**Comment by sdadasds** [comment]
similar thing with me: 

MCEdit version: 2.0.0-beta12
Python version: 2.7.12 (default, Jun 29 2016, 14:05:02) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
Platform: darwin
System version: Darwin-15.6.0-x86_64-i386-64bit
Processor: i386


------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2/main.py", line 226, in <module>  
  File "mcedit2/main.py", line 222, in main  
  File "mcedit2/util/profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2/main.py", line 193, in startup  
  File "mcedit2/editorapp.py", line 318, in __init__ (self is a MCEditApp)
  File "mcedit2/worldlist.py", line 237, in __init__ (self is a WorldListWidget)
  File "mcedit2/worldlist.py", line 319, in reloadRecentWorlds (self is a WorldListWidget)
  File "mceditlib/worldeditor.py", line 262, in getWorldInfo  
  File "mceditlib/findadapter.py", line 66, in findAdapter  
UnknownFormatError: Cannot detect type of file <Showed directory to my minecraft world here, I just dont want to show the directory>

**Comment by sdadasds** [comment]
scratch that I just fixed it

**Comment by ElpersonPL** [comment]
How?

**Comment by ElpersonPL** [comment]
HOW?

**Comment by ElpersonPL** [comment]
WTF WHY ANYBODY CANT HELP ME?!

**Comment by naor2013** [comment]
This is MCEdit-Unified's git.
MCEdit2's git is here: https://github.com/mcedit/mcedit2
