### ISSUE TITLE
Save Problems MCEdit 1.6.0.49

### ISSUE THREAD

**Issue by DomPrice** [Podshot/MCEdit-Unified#936]
Save Problems
MCEdit Version: 1.6.0.49
Minecraft Version the world was last opened in: MC Bedrock Ed iOS 1.4.3
Operating System: Windows 10

![capture](https://user-images.githubusercontent.com/857194/43116510-13f33b3c-8ed6-11e8-923d-fd7672dc05c6.PNG)

![capture2](https://user-images.githubusercontent.com/857194/43116512-15ef68e8-8ed6-11e8-8cb7-42437c6bbf4a.PNG)

Save world produces strange errors and sometimes the "Copying Chunks" part of the save process just keeps going and never ends. Thus I am unable to save any changes. Tried in multiple worlds. MCEdit recognizes the world type as Bedrock/PE 1.2.5.52.

**Comment by DomPrice** [comment]
Looks like the save process is hanging.
![capture3](https://user-images.githubusercontent.com/857194/43116988-839cdebe-8ed8-11e8-9957-6b6b5f4c1f79.PNG)

**Comment by gentlegiantJGC** [comment]
I too have noticed this issue. It appears seemingly randomly when trying to save. Windows 10 world running from source at the time of writing

```
[   ERROR][                    root.py:59]:Exception:
Traceback (most recent call last):
  File "C:\Users\%username%\Documents\GitHub\MCEdit-Unified\mceutils.py", line 53, in _alertException
    return func(*args, **kw)
  File "C:\Users\%username%\Documents\GitHub\MCEdit-Unified\leveleditor.py", line 1606, in saveFile
    if "Canceled" == showProgress("Copying chunks", copyChunks(), cancel=True):
  File "C:\Users\%username%\Documents\GitHub\MCEdit-Unified\albow\extended_widgets.py", line 359, in showProgress
    if widget.present():
  File "C:\Users\%username%\Documents\GitHub\MCEdit-Unified\albow\widget.py", line 538, in present
    self.root.run_modal(self)
  File "C:\Users\%username%\Documents\GitHub\MCEdit-Unified\albow\root.py", line 239, in run_modal
    self.gl_draw_all(self, (0, 0))
  File "C:\Users\%username%\Documents\GitHub\MCEdit-Unified\albow\widget.py", line 804, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "C:\Users\%username%\Documents\GitHub\MCEdit-Unified\albow\widget.py", line 811, in gl_draw_all
    self.draw_all(surface)
  File "C:\Users\%username%\Documents\GitHub\MCEdit-Unified\albow\widget.py", line 342, in draw_all
    self.draw(surface)
  File "C:\Users\%username%\Documents\GitHub\MCEdit-Unified\albow\extended_widgets.py", line 275, in draw
    amount = progressIterator.next()
  File "C:\Users\%username%\Documents\GitHub\MCEdit-Unified\leveleditor.py", line 1602, in copyChunks
    for _ in self.level.saveInPlaceGen():
  File "C:\Users\%username%\Documents\GitHub\MCEdit-Unified\pymclevel\leveldbpocket.py", line 1098, in saveInPlaceGen
    for chunk in self._loadedChunks.itervalues():
RuntimeError: dictionary changed size during iteration
```

**Comment by gentlegiantJGC** [comment]
In my case it produces the dialogue box which if you click okay to then try saving again it seems to save fine.

@DomPrice have you tried leaving it to save for a little while (I don't know how much you are saving). As long as the number on the left is going up it should eventually finish. The 0 on the right should show the maximum amount of chunks which will give the estimated time to finish but that was not implemented in the build you are running so it shows a negative time. (I have fixed this bug and should be fixed in the next test build)

**Comment by DomPrice** [comment]
I have allowed it to run and that’s when I get the dictionary changed size error. I will give the update a try when it hits and let you know if that helped.

**Comment by gentlegiantJGC** [comment]
This should hopefully be fixed with the commit that was just referenced. If you experience the issues in the next test build reopen the issue and let me know
