### ISSUE TITLE
TypeError: 'PySide.QtGui.QLineEdit.setText' called with wrong argument types:

### ISSUE THREAD

**Issue by cemmao** [Podshot/MCEdit-Unified#942]
#### How to reproduce:
i don't know how to fix this and so far i haven't found anything online to help. if anyone could help i would really appeciate it. i have uninstalled both minecraft and mcedit and it has not helped. thank you 
An error occurred while opening C:\Users\cemma\AppData\Roaming\.minecraft\saves\pokemon
'PySide.QtGui.QLineEdit.setText' called with wrong argument types:
  PySide.QtGui.QLineEdit.setText(list)
Supported signatures:
  PySide.QtGui.QLineEdit.setText(unicode)

Traceback (most recent call last):
  File "mcedit2\editorapp.py", line 790, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 430, in __init__ (self is a EditorSession)
  File "mcedit2\panels\worldinfo.py", line 90, in __init__ (self is a WorldInfoPanel)
  File "mcedit2\panels\worldinfo.py", line 97, in updatePanel (self is a WorldInfoPanel)
  File "mcedit2\panels\worldinfo.py", line 115, in _updatePanel (self is a WorldInfoPanel)
TypeError: 'PySide.QtGui.QLineEdit.setText' called with wrong argument types:
  PySide.QtGui.QLineEdit.setText(list)
Supported signatures:
  PySide.QtGui.QLineEdit.setText(unicode)

## Read before submitting
If we are not able to reproduce the error, we may ask for you to submit a world so we can test it. Same process for schematics.
If you have included enough information for each section, please delete the above header and all the text below.

**Comment by freundTech** [comment]
This seems to be about mcedit2 instead of mcedit unified. You can find the mcedit2 repository here: https://github.com/mcedit/mcedit2
