### ISSUE TITLE
IndexError: index 65535 is out of bounds for axis 0 with size 4096

### ISSUE THREAD

**Issue by RossComputerGuy** [Podshot/MCEdit-Unified#950]
MCEdit Unified bug report template. For MCEdit 2.0 bugs see here : https://github.com/mcedit/mcedit2
#### Description of Issue:
IndexError: index 65535 is out of bounds for axis 0 with size 4096
#### A screenshot or full text of the error from the console:
```
Traceback (most recent call last):
  File "/tmp/release-master/MCEdit-Unified/renderer.py", line 3804, in workOnChunk
  File "/tmp/release-master/MCEdit-Unified/renderer.py", line 3785, in calcFacesForChunkRenderer
  File "/tmp/release-master/MCEdit-Unified/renderer.py", line 385, in calcFaces
  File "/tmp/release-master/MCEdit-Unified/renderer.py", line 904, in calcFacesForChunkRenderer
  File "/tmp/release-master/MCEdit-Unified/renderer.py", line 1053, in calcHighDetailFaces
IndexError: index 65535 is out of bounds for axis 0 with size 4096
Destination:  _Vector(x=-498, y=1, z=-1297)
[   ERROR][                    root.py:62]:Exception:
Traceback (most recent call last):
  File "/tmp/release-master/MCEdit-Unified/mceutils.py", line 56, in _alertException
  File "/tmp/release-master/MCEdit-Unified/editortools/clone.py", line 1085, in confirm
  File "/tmp/release-master/MCEdit-Unified/leveleditor.py", line 3141, in addOperation
  File "/tmp/release-master/MCEdit-Unified/leveleditor.py", line 3152, in performWithRetry
  File "/tmp/release-master/MCEdit-Unified/editortools/clone.py", line 217, in perform
  File "/tmp/release-master/MCEdit-Unified/editortools/clone.py", line 142, in perform
  File "/tmp/release-master/MCEdit-Unified/albow/extended_widgets.py", line 360, in showProgress
  File "/tmp/release-master/MCEdit-Unified/albow/widget.py", line 549, in present
  File "/tmp/release-master/MCEdit-Unified/albow/root.py", line 233, in run_modal
  File "/tmp/release-master/MCEdit-Unified/albow/widget.py", line 790, in gl_draw_all
  File "/tmp/release-master/MCEdit-Unified/albow/widget.py", line 797, in gl_draw_all
  File "/tmp/release-master/MCEdit-Unified/albow/widget.py", line 358, in draw_all
  File "/tmp/release-master/MCEdit-Unified/albow/extended_widgets.py", line 276, in draw
  File "/tmp/release-master/MCEdit-Unified/pymclevel/block_copy.py", line 163, in copyBlocksFromIter
  File "/tmp/release-master/MCEdit-Unified/pymclevel/level.py", line 663, in chunkChanged
  File "/tmp/release-master/MCEdit-Unified/pymclevel/infiniteworld.py", line 261, in generateHeightMap
  File "/tmp/release-master/MCEdit-Unified/pymclevel/level.py", line 31, in computeChunkHeightMap
IndexError: index 65535 is out of bounds for axis 0 with size 4096
```
#### How to reproduce:
Import a NBT structure exported from a 1.12 world that has blocks from the MS Gundam Mod.

**Comment by gentlegiantJGC** [comment]
I think this issue was fixed a while ago in the source code but you have the version off the website which is older. There hasn't been a testing release built in quite a while so your best bet might be to run from source. Hopefully we will have a test build made for linux soon which will fix your issue

**Comment by RossComputerGuy** [comment]
It works.

**Comment by n0099** [comment]
This will also cause by a .nbt export with a large selection or contains too many nbt data, after exporting them as a `.schematic` file, this error is gone.
Note by default the file type of export file in the save file dialog on windows is `.nbt` not the `.schematic`
