### ISSUE TITLE
MCEdit Crashing

### ISSUE THREAD

**Issue by Lolguy17** [Podshot/MCEdit-Unified#955]
MCEdit Unified bug report template. For MCEdit 2.0 bugs see here : https://github.com/mcedit/mcedit2
#### A screenshot or full text of the error from the console:MCEdit version: 2.0.0-beta14
Python version: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]
Platform: win32
System version: Windows-10-10.0.17134
Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.6
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.6.0 NVIDIA 388.13 (4, 6)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 650/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\editorsession.py", line 1643, in viewOffsetChanged (self is a EditorTab)
  File "mcedit2\worldview\minimap.py", line 187, in currentViewMatrixChanged (self is a MinimapWorldView)
  File "mcedit2\util\raycast.py", line 30, in rayCastInBounds  
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\util\raycast.py", line 77, in rayCast  
  File "mcedit2\util\raycast.py", line 215, in advanceToChunk  
  File "mceditlib\worldeditor.py", line 831, in getChunk (self is a WorldEditorDimension)
  File "mceditlib\worldeditor.py", line 499, in getChunk (self is a WorldEditor)
  File "mceditlib\cachefunc.py", line 77, in __call__  
  File "mceditlib\worldeditor.py", line 477, in _getChunkDataRaw (self is a WorldEditor)
  File "mceditlib\anvil\adapter.py", line 922, in readChunk (self is a AnvilWorldAdapter)
AnvilChunkFormatError: [Errno Error loading chunk: KeyError('Key Blocks not found.',)] None: <traceback object at 0x1074A8C8>
#### How to reproduce:after downloading open mcedit2-win32 open it in win rar and select mcedit2-win32, then take mcedit2.exe and mcedit2files and select them both and bring them onto your home screen. then go to minecrafts file location and next to minecraft and desktop.ini make a new folder called mcedit. then  take mcedit2.exe and mcedit2files from before and put them in that folder.
then open minecraft go onto a world, then run mcedit, select the world to  edit and then the error will show up.

## Read before submitting
If we are not able to reproduce the error, we may ask for you to submit a world so we can test it. Same process for schematics.
If you have included enough information for each section, please delete the above header and all the text below.

**Comment by Podshot** [comment]
This is a bug with MCEdit 2.0 which is a separate project. Please report it at the correct GitHub repository: https://github.com/mcedit/mcedit2
