### ISSUE TITLE
MCEdit 2.0.0 and 0.1.7.1 crashes when opening worlds opened by 1.13.2

### ISSUE THREAD

**Issue by MatthewStevenGo** [Podshot/MCEdit-Unified#961]
MCEdit Unified bug report template. For MCEdit 2.0 bugs see here : https://github.com/mcedit/mcedit2
#### Operating System: Windows 10 Professional

How the error started:
= Launch the 1.13.2.
= Open the world that is previously opened in 1.12.2 or lower.
= Things in the world went all right until..... Opening the world in question using MCEdit.
Alternative:
= Try opening the old world affected by the 1.13.2 update using the old Minecraft version (1.12.2 and below)
= And then the world is, boom, blank.

Here is a log:

MCEdit version: 2.0.0-beta6
Python version: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-10-10.0.17134
Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.6
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.6.0 NVIDIA 388.57 (4, 6)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce 610M/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\worldlist.py", line 476, in loadTimerFired (self is a WorldListWidget)
  File "mcedit2\rendering\chunkloader.py", line 205, in next (self is a ChunkLoader)
  File "mcedit2\rendering\chunkloader.py", line 244, in _loadChunks (self is a ChunkLoader)
  File "mcedit2\rendering\chunkloader.py", line 275, in _loadChunk (self is a ChunkLoader)
  File "mceditlib\worldeditor.py", line 807, in getChunk (self is a WorldEditorDimension)
  File "mceditlib\worldeditor.py", line 495, in getChunk (self is a WorldEditor)
  File "mceditlib\cachefunc.py", line 77, in __call__  
  File "mceditlib\worldeditor.py", line 473, in _getChunkDataRaw (self is a WorldEditor)
  File "mceditlib\anvil\adapter.py", line 892, in readChunk (self is a AnvilWorldAdapter)
  File "src\mceditlib\nbt.pyx", line 569, in mceditlib.nbt.load (src/mceditlib/nbt.c:12098)  
  File "src\mceditlib\nbt.pyx", line 662, in mceditlib.nbt.load_compound (src/mceditlib/nbt.c:12976)  
  File "src\mceditlib\nbt.pyx", line 669, in mceditlib.nbt.load_named (src/mceditlib/nbt.c:13053)  
  File "src\mceditlib\nbt.pyx", line 786, in mceditlib.nbt.load_tag (src/mceditlib/nbt.c:14277)  
  File "src\mceditlib\nbt.pyx", line 662, in mceditlib.nbt.load_compound (src/mceditlib/nbt.c:12976)  
  File "src\mceditlib\nbt.pyx", line 669, in mceditlib.nbt.load_named (src/mceditlib/nbt.c:13053)  
  File "src\mceditlib\nbt.pyx", line 786, in mceditlib.nbt.load_tag (src/mceditlib/nbt.c:14277)  
  File "src\mceditlib\nbt.pyx", line 662, in mceditlib.nbt.load_compound (src/mceditlib/nbt.c:12976)  
  File "src\mceditlib\nbt.pyx", line 668, in mceditlib.nbt.load_named (src/mceditlib/nbt.c:13041)  
  File "src\mceditlib\nbt.pyx", line 709, in mceditlib.nbt.load_name (src/mceditlib/nbt.c:13470)  
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 6: invalid start byte

**Comment by gentlegiantJGC** [comment]
Read the first line of your report

**Comment by MatthewStevenGo** [comment]
You mean the link?
