### ISSUE TITLE
Can't run it under Manjaro Linux.

### ISSUE THREAD

**Issue by Rencer** [Podshot/MCEdit-Unified#982]
I installed MCEdit from the AUR repo under Manjaro Linux (18.0.4).
When I start the program it shows the splash screen and then crash.
Running it from the terminal reveal the problem:

```
Running in fixed mode. Support files are in your Documents folder.
pygame 1.9.5
Hello from the pygame community. https://www.pygame.org/contribute.html
Splash load...
[ ****** ] ~~~~~~~~~~ Starting MCEdit-Unified v1.5.6.0
Traceback (most recent call last):
  File "/usr/lib/mcedit/mcedit.py", line 118, in <module>
    import keys
  File "/usr/lib/mcedit/keys.py", line 4, in <module>
    import albow
  File "/usr/lib/mcedit/albow/__init__.py", line 17, in <module>
    from albow.shell import Shell
  File "/usr/lib/mcedit/albow/shell.py", line 5, in <module>
    from root import RootWidget
  File "/usr/lib/mcedit/albow/root.py", line 23, in <module>
    from pymclevel.box import Vector
  File "/usr/lib/mcedit/pymclevel/__init__.py", line 10, in <module>
    from indev import MCIndevLevel
  File "/usr/lib/mcedit/pymclevel/indev.py", line 63, in <module>
    from level import MCLevel
  File "/usr/lib/mcedit/pymclevel/level.py", line 12, in <module>
    import materials
  File "/usr/lib/mcedit/pymclevel/materials.py", line 454, in <module>
    alphaMaterials.addJSONBlocksFromFile("minecraft.json")
  File "/usr/lib/mcedit/pymclevel/materials.py", line 327, in addJSONBlocksFromFile
    f = file(path)
IOError: [Errno 2] No such file or directory: 'pymclevel/minecraft.json'
```

P.S.: I looked through the folders where MCEdit is installed, and in fact the _minecraft.json_ file is there in the pymclevel directory.

**Comment by freundTech** [comment]
I can't reproduce the problem. I just reinstalled mcedit from AUR on arch linux and it starts fine.

You could try if the mcedit-git package produces the same error or try running from source (see readme file)

**Comment by Rencer** [comment]
Sorry for the late reply, but I didn't used McEdit for a while.
Today I installed the 'mcedit 1.5.6.0-1' from AUR tho' it is outdated, but now it is working.
Than I installed the 'mcedit-git 201800909-2" from AUR and that works very well too.
Thanks. Closing it.
