### ISSUE TITLE
Cant download/install McEdit

### ISSUE THREAD

**Issue by QuarixCZ** [Podshot/MCEdit-Unified#985]
Description of Issue: Can't download MCEdit
MCEdit Version: 1.5.6.0
Operating System: Ubuntu 19.04
A screenshot or full text of the error from the console:
 ```
Detecting state of the dependencies...
Traceback (most recent call last):
  File "../bin3/mcedit-1.5.6.0/install.py", line 994, in <module>
  File "../bin3/mcedit-1.5.6.0/install.py", line 431, in o0O0Oooo0O
ImportError: No module named pkg_resources
```

**Comment by gentlegiantJGC** [comment]
Try reading the readme

**Comment by QuarixCZ** [comment]
Well, now i got this:
`Starting MCEdit...
Running in fixed mode. Support files are in your Documents folder.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/release-master/MCEdit-Unified/__main__.py", line 38, in <module>
  File "/tmp/release-master/MCEdit-Unified/mcedit.py", line 13, in <module>
  File "/tmp/release-master/MCEdit-Unified/splash.py", line 10, in <module>
ImportError: No module named pygame
`

**Comment by QuarixCZ** [comment]
Got it working somehow.
