### ISSUE TITLE
Crashes when opening MCPE 1.13.0 worlds

### ISSUE THREAD

**Issue by CLEVERCATMAN** [Podshot/MCEdit-Unified#994]
Here is the info

Game Version: PE : 1.13.0.34.0
mcedit.main MCEdit exited with errors.
[   ERROR][                  root.py:1013]:MCEdit version Unified v1.6.0.53-testing %s Minecraft 1.8-1.11.2 | PE 0.11
[   ERROR][                  root.py:1016]:'Key val not found.'
Traceback (most recent call last):
  File "mcedit.py", line 1010, in main
  File "mcedit.py", line 887, in main
  File "albow\root.py", line 174, in run
  File "albow\root.py", line 239, in run_modal
  File "albow\widget.py", line 804, in gl_draw_all
  File "albow\widget.py", line 804, in gl_draw_all
  File "albow\widget.py", line 804, in gl_draw_all
  File "albow\widget.py", line 804, in gl_draw_all
  File "albow\widget.py", line 801, in gl_draw_all
  File "albow\openglwidgets.py", line 22, in gl_draw_self
  File "albow\openglwidgets.py", line 28, in gl_draw_viewport
  File "viewports\camera.py", line 1922, in gl_draw
  File "viewports\camera.py", line 1944, in render
  File "viewports\camera.py", line 346, in updateBlockFaceUnderCursor
  File "raycaster.py", line 85, in firstBlock
  File "pymclevel\infiniteworld.py", line 547, in blockAt
  File "pymclevel\leveldbpocket.py", line 1003, in getChunk
  File "pymclevel\leveldbpocket.py", line 655, in loadChunk
  File "pymclevel\leveldbpocket.py", line 470, in _readChunk
  File "pymclevel\leveldbpocket.py", line 1971, in add_data
  File "pymclevel\leveldbpocket.py", line 1925, in _read_block_storage
  File "pymclevel\_nbt.pyx", line 478, in pymclevel._nbt._TAG_Compound.__getitem__
    raise KeyError("Key %s not found." % key)
KeyError: 'Key val not found.'
Press RETURN or close this window to dismiss.

**Comment by gentlegiantJGC** [comment]
MCEdit does not support 1.13 worlds

**Comment by zillion42** [comment]
Hi,

is there an update planned ? I really enjoy MCEdit-Unified, so does my 7 year old son :)

Thx for the hard work.
